### ISSUE TITLE
according to example, use a Script to send buttons, work well in 1-5 mins, then crash.

### ISSUE THREAD

**Issue by Zhangdaoning** [ktnrg45/pyremoteplay#5]
Hi ktnrg45,

**I have tried the example, and I create a QThread to control button,  it could work well for about 10 mins, then crashed. Here is my code:**

```
def run(self):
        while 1:
            self.msleep(10)
            if self.is_Game_Ing and not self.is_33:
                print('CIRCLE')
                self.device.controller.button('CIRCLE', 'press')
                self.msleep(100)
                self.device.controller.button('CIRCLE', 'release')
                self.msleep(500)
                print('CROSS')
                self.device.controller.button('CROSS', 'press')
                self.msleep(100)
                self.device.controller.button('CROSS', 'release')
                self.msleep(1000)
                print('LEFT')
                self.device.controller.button('LEFT', 'press')
                self.msleep(100)
                self.device.controller.button('LEFT', 'release')
                self.msleep(1000)
```

**It will work for 1-5mins, and the Error code shows up,and the thread WORKER, device.session.is_running still True. Here is my error code:**

```
Fatal write error on datagram transport
protocol: <pyremoteplay.stream.RPStream.Protocol object at 0x000001BF00552BC0>
transport: <_ProactorDatagramTransport fd=4140 read=<_OverlappedFuture pending overlapped=<pending, 0x1bf00595480> cb=[_ProactorDatagramTransport._loop_reading()]> write=<_OverlappedFuture finished result=37>>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 512, in _loop_writing
    assert fut is self._write_fut
AssertionError

Exception in thread Thread-2 (__worker):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\controller.py", line 61, in __worker
    self.update_sticks()
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\controller.py", line 113, in update_sticks
    self._session.stream.send_feedback(
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 195, in send_feedback
    self.send(msg.bytes(self.cipher, True))
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 206, in send
    self._protocol.sendto(msg, (self._host, self._port))
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 66, in sendto
    self.transport.sendto(data, addr)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 498, in sendto
    self._buffer.append((bytes(data), addr))
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by Zhangdaoning** [comment]
Secend Time, Error code:

```
Fatal write error on datagram transport
protocol: <pyremoteplay.stream.RPStream.Protocol object at 0x000001A771BB1B10>
transport: <_ProactorDatagramTransport fd=3772 read=<_OverlappedFuture pending overlapped=<pending, 0x1a77a709510> cb=[_ProactorDatagramTransport._loop_reading()]> write=<_OverlappedFuture finished result=37>>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 512, in _loop_writing
    assert fut is self._write_fut
AssertionError
Task exception was never retrieved
future: <Task finished name='Task-721' coro=<Session.run_io() done, defined at C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\session.py:628> exception=AttributeError("'NoneType' object has no attribute 'append'")>
Traceback (most recent call last):
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\session.py", line 634, in run_io
    return await self.loop.run_in_executor(
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 245, in _handle_later
    self._recv_data(packet)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 261, in _recv_data
    self.proto.handle(params["data"])
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\protobuf.py", line 188, in handle
    self._ack(msg, channel)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\protobuf.py", line 121, in _ack
    self._stream.send_data(msg, chunk_flag, channel, proto=True)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 179, in send_data
    self.send(msg.bytes(self.cipher, False, advance_by))
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 206, in send
    self._protocol.sendto(msg, (self._host, self._port))
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 66, in sendto
    self.transport.sendto(data, addr)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 498, in sendto
    self._buffer.append((bytes(data), addr))
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by Zhangdaoning** [comment]
when the error occurs:

device.session.is_running is True

frame = self.device.session.receiver.get_latest_video_frame() still running, but frame is stuck.

i guess something went wrong about asyncio.

How can i avoid it, or handle the exception to restart the loop task. I do not want my program crash...

**Comment by Zhangdaoning** [comment]
**This my whole code:**

```
import asyncio
import threading
import atexit
import time
import cv2
from skimage.metrics import structural_similarity
from pyremoteplay import RPDevice
from pyremoteplay.receiver import QueueReceiver

def comparePic(imageA, imageB):
    # 灰度图片比较
    grayA = cv2.cvtColor(imageA, cv2.COLOR_BGR2GRAY)
    grayB = cv2.cvtColor(imageB, cv2.COLOR_BGR2GRAY)
    (score, diff) = structural_similarity(grayA, grayB, full=True)
    return float(score)

def stop(device, thread):
    loop = device.session.loop
    device.disconnect()
    loop.stop()
    thread.join(3)
    print("stopped")


def worker(device, user):
    loop = asyncio.new_event_loop()
    receiver = QueueReceiver()
    device.create_session(user, receiver=receiver, loop=loop, resolution='540p', fps=30)
    task = loop.create_task(device.connect())
    loop.run_until_complete(task)
    loop.run_forever()


def start(ip_address):
    """Return device. Start Remote Play session."""
    device = RPDevice(ip_address)
    if not device.get_status():  # Device needs a valid status to get users
        print("No Status")
        return None
    users = device.get_users()
    if not users:
        print("No users registered")
        return None
    user = users[0]  # Gets first user name
    thread = threading.Thread(target=worker, args=(device, user), daemon=True)
    thread.start()
    atexit.register(
        lambda: stop(device, thread)
    )  # Make sure we stop the thread on exit.
    return device

ip_address = '192.168.108.253'
device = start(ip_address)
time.sleep(3)
device.controller.start()
while 1:
    time.sleep(0.01)
    if device.session:
        print('========================')
        print(device.session.state)
        print(device.session.is_running)
        # video_frames = device.session.receiver.video_frames
        # print(video_frames)
        # if len(video_frames) > 0:
        # frame = video_frames[0]
        frame = device.session.receiver.get_latest_video_frame()
        if frame:
            img = frame.to_ndarray(format='bgr24')
            # cv2.imshow("pic", img)
            # if cv2.waitKey(1) & 0xFF == ord('q'):
            #     cv2.destroyAllWindows()
            #     break

            is_CtrlMsgbox = comparePic(img[259:278, 339:608],cv2.imread('Pics/BasicPic/img_is_CtrlMsgbox.png')) > 0.8
            is_Main = comparePic(img[45:60, 659:669], cv2.imread('Pics/BasicPic/img_is_Main.png')) > 0.8
            is_Game_Ing = comparePic(img[26:33, 852:867],cv2.imread('Pics/BasicPic/img_is_Game_Ing.png')) > 0.8
            is_33 = comparePic(img[181:193, 795:844], cv2.imread('Pics/BasicPic/img_is_33.png')) > 0.8
            is_55_Left = comparePic(img[181:193, 115:162], cv2.imread('Pics/BasicPic/img_is_55_Left.png')) > 0.8
            is_55_Right = comparePic(img[181:193, 795:842], cv2.imread('Pics/BasicPic/img_is_55_Right.png')) > 0.8
            is_55 = is_55_Left or is_55_Right

            if is_CtrlMsgbox:
                device.controller.button('OPTIONS', 'press')
                time.sleep(0.1)
                device.controller.button('OPTIONS', 'release')
                time.sleep(2)
            if is_Game_Ing and not is_33:
                print('########CallPlay########')
                print('CIRCLE')
                device.controller.button('CIRCLE', 'press')
                time.sleep(0.1)
                device.controller.button('CIRCLE', 'release')
                time.sleep(0.5)
                print('CROSS')
                device.controller.button('CROSS', 'press')
                time.sleep(0.1)
                device.controller.button('CROSS', 'release')
                time.sleep(1)
                print('LEFT')
                device.controller.button('LEFT', 'press')
                time.sleep(0.1)
                device.controller.button('LEFT', 'release')
                time.sleep(1)
            elif is_Game_Ing and is_33:
                print('########Score########')
                print('TRIANGLE')
                device.controller.button('TRIANGLE', 'press')
                time.sleep(0.1)
                device.controller.button('TRIANGLE', 'release')
                time.sleep(3)
                print('CROSS')
                device.controller.button('CROSS', 'press')
                time.sleep(0.1)
                device.controller.button('CROSS', 'release')
                time.sleep(3)
                # playerName = getPlayerNameFromIMG(IMG.get(self.index))
                # shotTime = PLAYERTIME[playerName]
                # print(datetime.datetime.now(), self.index, playerName, shotTime)
                print('JOY RIGHT UP')
                device.controller.stick('RIGHT', 'Y', -1.0)
                time.sleep(0.1)
                device.controller.stick('RIGHT', 'Y', 0.0)
                time.sleep(1.15)
                print('SQUARE')
                device.controller.button('SQUARE', 'press')
                time.sleep(0.46)
                device.controller.button('SQUARE', 'release')
                time.sleep(0.5)
            elif is_Main:
                print('########Main########')
                for i in range(3):
                    print('Cross')
                    device.controller.button('Cross', 'press')
                    time.sleep(1.5)
                    device.controller.button('Cross', 'release')
                    time.sleep(0.1)
            else:
                print('########ELSE########')
                print('CIRCLE')
                device.controller.button('CIRCLE', 'press')
                time.sleep(0.1)
                device.controller.button('CIRCLE', 'release')
                time.sleep(1)
                print('JOY LEFT UP')
                device.controller.stick('LEFT', 'Y', -1.0)
                time.sleep(0.1)
                device.controller.stick('LEFT', 'Y', 0.0)
                time.sleep(0.5)
                print('Cross')
                device.controller.button('Cross', 'press')
                time.sleep(1.5)
                device.controller.button('Cross', 'release')
                time.sleep(0.1)



# Usage:
#
# Starting session:
# >> ip_address = '192.168.86.2' # ip address of Remote Play device
# >> device = start(ip_address)
#
# Retrieving latest video frames:
# >> device.session.receiver.video_frames
#
# Tap Controller Button:
# >> device.controller.button("cross", "tap")
#
# Start Controller Stick Worker
# >> device.controller.start()
#
# Emulate moving Left Stick all the way right:
# >> device.controller.stick("left", axis="x", value=1.0)
#
# Release Left stick:
# >> device.controller.stick("left", axis="x", value=0)
#
# Move Left stick diagonally left and down halfway
# >> device.controller.stick("left", point=(-0.5, 0.5))

```

**this is error code:**

`Fatal write error on datagram transport
protocol: <pyremoteplay.stream.RPStream.Protocol object at 0x000002819BB36E60>
transport: <_ProactorDatagramTransport fd=2692 read=<_OverlappedFuture pending overlapped=<pending, 0x2819bd475b0> cb=[_ProactorDatagramTransport._loop_reading()]> write=<_OverlappedFuture finished result=29>>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 512, in _loop_writing
    assert fut is self._write_fut
AssertionError
Task exception was never retrieved
future: <Task finished name='Task-739' coro=<Session.run_io() done, defined at C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\session.py:628> exception=AttributeError("'NoneType' object has no attribute 'append'")>
Traceback (most recent call last):
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\session.py", line 634, in run_io
    return await self.loop.run_in_executor(
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 245, in _handle_later
    self._recv_data(packet)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 261, in _recv_data
    self.proto.handle(params["data"])
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\protobuf.py", line 188, in handle
    self._ack(msg, channel)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\protobuf.py", line 121, in _ack
    self._stream.send_data(msg, chunk_flag, channel, proto=True)
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 179, in send_data
    self.send(msg.bytes(self.cipher, False, advance_by))
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 206, in send
    self._protocol.sendto(msg, (self._host, self._port))
  File "C:\Users\31378\Desktop\PycharmProjects\MTool\pyremoteplay\stream.py", line 66, in sendto
    self.transport.sendto(data, addr)
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 498, in sendto
    self._buffer.append((bytes(data), addr))
AttributeError: 'NoneType' object has no attribute 'append'`

**Comment by Zhangdaoning** [comment]
I tried on MacOS, error is:
```
AV Handler max queue size exceeded
Traceback (most recent call last):
  File "/Users/daoning/Desktop/register/test_pyremoteplay.py", line 153, in <module>
    device.controller.button('Cross', 'release')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyremoteplay/controller.py", line 166, in button
    self._send_event()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyremoteplay/controller.py", line 123, in _send_event
    self._session.stream.send_feedback(
AttributeError: 'NoneType' object has no attribute 'stream'
stopped
```

**Comment by Zhangdaoning** [comment]
I tried on Raspberry Pi 4B with Raspbian OS, It works well for long time.
Maybe Debian OS is stable.
